## Hub NGINX (webserver) Filebeat Configuration

filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/nginx/error.log
  fields:
    application: hub-webserver
    category: "nginx-errors"
  fields_under_root: true

- input_type: log
  paths:
    - /var/log/nginx/nginx-access.log
  fields:
    application: hub-webserver
    category: "access-log"
  fields_under_root: true

output.logstash:
  hosts: ["${HUB_LOGSTASH_HOST:logstash}:${HUB_LOGSTASH_PORT:5044}"]
  index: filebeat

logging.level: info